[phases.setup]
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "php83Extensions.pdo",
    "php83Extensions.pdo_sqlite",
    "php83Extensions.mbstring",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "php83Extensions.ctype",
    "php83Extensions.bcmath",
    "sqlite"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
    "chmod +x railway/*.sh",
    "./railway/init-app.sh"
]

[start]
cmd = "./railway/run-app.sh"
